### ISSUE TITLE
flame 1.17 compilation error

### ISSUE THREAD

**Issue by vmtest888** [ikbendewilliam/flutter_flame_architecture#1]
flame 1.17 compilation error

`
D:\work\source\flutter_flame_architecture\example>flutter  build web
Flutter assets will be downloaded from https://storage.flutter-io.cn. Make sure you trust this source!

Upgrading .gitignore
Target dart2js failed: ProcessException: Process exited abnormally with exit code 1:
../lib/src/game/simple_game_manager.dart:71:18:
Error: Type 'TapDownInfo' not found.
  void onTapDown(TapDownInfo event) {
                 ^^^^^^^^^^^
../lib/src/game/simple_game_manager.dart:81:16:
Error: Type 'TapUpInfo' not found.
  void onTapUp(TapUpInfo event) {
               ^^^^^^^^^
../lib/src/game/simple_game_manager.dart:91:21:
Error: Type 'ScaleStartInfo' not found.
  void onScaleStart(ScaleStartInfo event) {
                    ^^^^^^^^^^^^^^
../lib/src/game/simple_game_manager.dart:103:22:
Error: Type 'ScaleUpdateInfo' not found.
  void onScaleUpdate(ScaleUpdateInfo event) {
                     ^^^^^^^^^^^^^^^
../lib/src/game/simple_game_manager.dart:117:19:
Error: Type 'ScaleEndInfo' not found.
  void onScaleEnd(ScaleEndInfo event) {
`

Need to be added in simple_game_manager.dart
`
import 'package:flame/src/gestures/events.dart';
`

Very useful flame gui library, you can add more components when you have time, thank you for your hard work

**Comment by ikbendewilliam** [comment]
Sorry to hear this, I'm not very active atm in the packages as I'm very busy with projects. It seems you only need to add an import in `simple_game_manager.dart`. 
What you can try is forking this repo, increasing the version of flame used from 1.7 to 1.17 and running the example. Fix the obvious issues and if that works, you can add that repo to your project using a git url: 
```
  flutter_flame_architecture:
    git:
      url: https://github.com/your-url/flutter_flame_architecture
      ref: 33de3c1 # commit hash, change it to your latest hash
```

If this works you can create a PR and I will approve it unless I see major issues :-) 

I highly doubt I will be able to update it myself soon, so any help is appreciated highly!
